"""empty message

Revision ID: 09e61e6e23b6
Revises: b3fc43bb64e5
Create Date: 2018-12-11 18:22:02.607683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e61e6e23b6'
down_revision = 'b3fc43bb64e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area')
    # ### end Alembic commands ###
